### ISSUE TITLE
add resize to ale object list

### ISSUE THREAD

**Issue by rikiaosu** [ZenoABC/ALEI#19]
https://github.com/ZenoABC/ALEI/assets/150896202/bee01929-f9d1-4ad6-bad2-b3975dd467d3

https://github.com/ZenoABC/ALEI/assets/150896202/3c65a95e-a778-4eda-8fb3-fa0927b34986

add in style of this pls thanks

**Comment by LisABC** [comment]
You can now resize objbox in 4.9, it's still W.I.P as there also needs to be RPARAMS resizing to be done, but I lost my mind while trying to do it, I will try again later or delegate the work to somebody else

**Comment by LisABC** [comment]
First implemented in [4.9](https://github.com/ZenoABC/ALEI/commit/427098f0225168dace772b1ae06ffd4792e436a0), followed with [5.0](https://github.com/ZenoABC/ALEI/commit/47bcd8a852aca80547669a5902ac2d49d57299bd), thanks for suggesting.
