### ISSUE TITLE
Make ALEI 2!!!

### ISSUE THREAD

**Issue by Sinclair-Speccy** [ZenoABC/ALEI#22]
![IMG_7587](https://github.com/ZenoABC/ALEI/assets/73531055/369f7be8-b941-4d82-acfa-17ecf62722dd)

**Comment by LisABC** [comment]
Please no troll issue, ty

**Comment by Sinclair-Speccy** [comment]
L

**Comment by eaglePB2** [comment]
Hi, there would not really have ALEI 2 at the moment, maybe you can ask this again when eric released his PB 2.5 level editor out :D
